<div
    class="full-page"
    data-type="component-text"
    data-preview=""
    data-aoraeditor-title="All Page" data-aoraeditor-categories="Appointment Page">
    @include(theme('snippets.components._appointment_hero_area'))
    @include(theme('snippets.components._appointment_feature_01'))
    @include(theme('snippets.components._appointment_feature_02'))
    @include(theme('snippets.components._appointment_feature_03'))
    @include(theme('snippets.components._appointment_feature_04'))
    @include(theme('snippets.components._appointment_feature_05'))
    @include(theme('snippets.components._appointment_feature_06'))
    @include(theme('snippets.components._appointment_feature_07'))
</div>
@include(theme('snippets.components._appointment_hero_area'))
@include(theme('snippets.components._appointment_feature_01'))
@include(theme('snippets.components._appointment_feature_02'))
@include(theme('snippets.components._appointment_feature_03'))
@include(theme('snippets.components._appointment_feature_04'))
@include(theme('snippets.components._appointment_feature_05'))
@include(theme('snippets.components._appointment_feature_06'))
@include(theme('snippets.components._appointment_feature_07'))
